export const selectValuesFormValues = [
    {value: 'alimentación', displayName:'Alimentación' },
    {value: 'transporte', displayName:'Transporte' },
    {value: 'hogar', displayName:'Hogar' },
    {value: 'familia', displayName:'Familia' },
    {value: 'diversion', displayName:'Diversión' },
    {value: 'deudas', displayName:'Deudas' },
    {value: 'telefonia', displayName:'Telefonía' },
    {value: 'despensa', displayName:'Despensa' },
    {value: 'internet', displayName:'Internet' },
    {value: 'electronica', displayName:'Electroníca' },
    {value: 'mascotas', displayName:'Mascotas' },
    {value: 'streaming', displayName:'Streaming' },
    {value: 'servicios profesionales', displayName:'Servicos profesionales' },
    {value: 'otros', displayName:'Otros' },
];